spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ocorrenciaescolar
    username: root
    password: senai
    driver-class-name: org.postgresql.Driver

  jpa:
    hiberate:
      ddl-auto: validate
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      enabled: true