spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ocorrenciaescolar
    username: postgres
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      enabled: true
  security:
    token:
      secret:
        ${JWT_SECRET}